seed: 1024
data:
    name: cityscapes
    root_path: /Users/ajaydyavathi/My_Cityscapes/dataset/cityscapes
    train_split: train
    val_split: val
    img_height: 256
    img_width: 512
model:
    architecture: segnet
    n_classes: 20
training:
    batch_size: 8
    n_workers: 1
    optimizer: 
        name: adam
        lr: 1.0e-4
    scheduler:
        name: constant
    loss:
        name: focal
    resume: false
    checkpoint: false
    train_epochs: 100
    print_interval: 5
    val_interval: 25
